/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }

//    @Test public void analyzingWeatherData() {
//
//        int[][] exampleArr = {
//                {10,20,22,15,17},
//                {12,15,20,20,15},
//                {23,15,20,22,15}
//        };
//        String expectedResult = "Never saw the temperature: 11\nNever saw the temperature: 13\nNever saw the temperature: 14\nNever saw the temperature: 16\nNever saw the temperature: 18\nNever saw the temperature: 19\nNever saw the temperature: 21\n";
//        assertEquals("This array should find the min and max of the temparature and return the temperatures that are not registered for any day", expectedResult , new App.analyzingWeatherData(exampleArr) );
    }

//    @Test public void tally() {
//        Library classUnderTest = new Library();
//        assertEquals("", , );
//    }

}
