/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package inheritance;

import java.util.ArrayList;
import java.util.List;

public class Library {
    public static void main(String[] args) {

        Restaurant res = new Restaurant("mac", 4, 3);
        Review rev1 = new Review("Amazing", "Anas", 3);
        Review rev2 = new Review("Nice", "Majd", 4);
        res.addReview(rev1);
        res.addReview(rev2);
        res.toString();

        ArrayList<String> movies = new ArrayList<String>();
        Theater th = new Theater("City mall Theater",movies);
        movies.add("matrix");
        movies.add("potato");
        movies.add("lord of the rings");
        movies.add("inception");

        Review rev3 = new Review("Amazing", "Anas", 3);
        Review rev4 = new Review("Nice", "Majd", 4, "Inception");
        th.addReview(rev3);
        th.addReview(rev4);

        System.out.println(th.reviewsList.toString());

//        th.removeMovie("potato");
//        th.addMovie("taken");

//        System.out.println(th);
        System.out.println(th.getMovies());

        System.out.println(th.reviewsList);
//
//
//        Shop sh = new Shop("potato", "potatos are the best", 4);
//        Review r1 = new Review("hehehe", "Anas" , 4);
//        Review r2 = new Review("muahahah", "Saify" , 3);
//        Review r3 = new Review("blah blah", "Majd" , 2);
//        sh.addReview(r1);
//        sh.addReview(r2);
//        sh.addReview(r3);
//        System.out.println(sh);
//        System.out.println(sh.reviewsList);

        System.out.println("I am working fine");
    }
}
