/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.inheritance;

public class Library {
    public static void main(String[] args) {

        Restaurant res = new Restaurant("mac", 4, 3);
        Review rev1 = new Review("Amazing", "Anas", 3);
        Review rev2 = new Review("Nice", "Majd", 4);
        res.addReview(rev1);
        res.addReview(rev2);
        res.toString();

    }
}
