package linter;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testNoErrorsFile() {
        String actual = App.readJS("src/test/resources/noErrorFil.js");
        assertTrue(!actual.contains("Missing semicolon."));

    }

    @Test
    public void testOneErrorFile() {
        String actual = App.readJS("src/test/resources/oneErrorFile.js");
        assertTrue(actual.contains("Missing semicolon."));
    }

    @Test
    public void testFewErrorsFile() {
        String actual = App.readJS("src/test/resources/fewErrorrsFile.js");
        assertTrue(actual.contains("Missing semicolon."));
    }

    @Test
    public void testManyErrorsFile() {
        String actual = App.readJS("src/test/resources/manyErrorsFile.js");
        assertTrue(actual.contains("Missing semicolon."));
    }

    @Test
    public void testEmptyFile() {
        String actual = App.readJS("src/test/resources/emptyFile.js");
        assertEquals("",actual);
    }


}
